=== freezzer/flow/trunk/server/model/model.dtd
<!ELEMENT define (model|view|permission|comment|import|interface|rules)*>
<!ELEMENT rules (rule|rules)*>
<!ATTLIST rules
         use CDATA #IMPLIED
         name CDATA #IMPLIED
         type CDATA #IMPLIED
         events CDATA #IMPLIED
         path CDATA #IMPLIED>
<!ELEMENT rule (#PCDATA)>
<!ATTLIST rule
         use CDATA #IMPLIED
         name CDATA #IMPLIED
         label CDATA #IMPLIED
         pattern CDATA #IMPLIED
         maxlength CDATA #IMPLIED
         mandatory CDATA #IMPLIED
         path CDATA #IMPLIED>
<!ELEMENT interface (#PCDATA)>
<!ELEMENT comment (#PCDATA)>
<!ELEMENT import (bean)*>
<!ATTLIST import
        file CDATA #REQUIRED>

<!ELEMENT model (bean)*>
<!ATTLIST model
        package CDATA #REQUIRED>
<!ELEMENT bean (field|collection|bean)*>
<!ATTLIST bean
        create CDATA #IMPLIED
        name CDATA #REQUIRED
        persistent CDATA #IMPLIED
        unique-key CDATA #IMPLIED>
<!ELEMENT field (#PCDATA)>
<!ATTLIST field
        create CDATA #IMPLIED
        name CDATA #REQUIRED
        type CDATA #IMPLIED
        reference CDATA #IMPLIED>
<!ELEMENT collection (bean)*>
<!ATTLIST collection
        create CDATA #IMPLIED
        name CDATA #REQUIRED
        type CDATA #IMPLIED>
<!ELEMENT permission (view|lister|tree_editor|panel)*>
<!ATTLIST permission
        package CDATA #IMPLIED
        name CDATA #REQUIRED>
<!ELEMENT view (tree_editor|panel|lister|tabbed_application_panel|permission)*>
<!ATTLIST view
        package CDATA #IMPLIED
        >
<!ELEMENT tree_editor (tree_node|command)*>
<!ATTLIST tree_editor
        name CDATA #REQUIRED
        type CDATA #REQUIRED
        label CDATA #REQUIRED>
<!ELEMENT tree_node (tree_node|command)*>
<!ATTLIST tree_node
        icon CDATA #IMPLIED
        label CDATA #REQUIRED
        lister CDATA #IMPLIED
        open CDATA #IMPLIED
        panel CDATA #IMPLIED
        path CDATA #REQUIRED
        type CDATA #IMPLIED>
<!ELEMENT command (#PCDATA)>
<!ATTLIST command
        editor CDATA #IMPLIED
        icon CDATA #IMPLIED
        label CDATA #REQUIRED
        name CDATA #IMPLIED
        lister CDATA #IMPLIED
        permitted CDATA #IMPLIED
        default CDATA #IMPLIED
        event CDATA #IMPLIED
        use CDATA #IMPLIED>
<!ELEMENT panel (panel|input|lookup)*>
<!ATTLIST panel
        border CDATA #IMPLIED
        editable CDATA #IMPLIED
        gap CDATA #IMPLIED
        labelwidth CDATA #IMPLIED
        inputwidth CDATA #IMPLIED
        label CDATA #IMPLIED
        name CDATA #IMPLIED
        path CDATA #IMPLIED
        use CDATA #IMPLIED
        x CDATA #IMPLIED
        y CDATA #IMPLIED
        w CDATA #IMPLIED
        h CDATA #IMPLIED>
<!ELEMENT input (lister)*>
<!ATTLIST input
        x CDATA #IMPLIED
        y CDATA #IMPLIED
        w CDATA #IMPLIED
        h CDATA #IMPLIED
        editable CDATA #IMPLIED
        labelwidth CDATA #IMPLIED
        label CDATA #REQUIRED
        path CDATA #REQUIRED
        default CDATA #IMPLIED
        type CDATA #IMPLIED>
<!ELEMENT lookup (lister)*>
<!ATTLIST lookup
        x CDATA #IMPLIED
        y CDATA #IMPLIED
        w CDATA #IMPLIED
        h CDATA #IMPLIED
        guirep CDATA #IMPLIED
        editor CDATA #IMPLIED
        lister CDATA #IMPLIED
        provider CDATA #IMPLIED
        labelwidth CDATA #IMPLIED
        label CDATA #REQUIRED
        path CDATA #REQUIRED
        type CDATA #IMPLIED>
<!ELEMENT provider (#PCDATA)>
<!ATTLIST provider
        query CDATA #IMPLIED
        name CDATA #IMPLIED
        use CDATA #IMPLIED
        path CDATA #IMPLIED
        type CDATA #REQUIRED>

<!ELEMENT lister (command|column|provider)*>
<!ATTLIST lister
        label CDATA #IMPLIED
        name CDATA #IMPLIED
        use CDATA #IMPLIED
        type CDATA #REQUIRED>
<!ELEMENT column (#PCDATA)>
<!ATTLIST column
        label CDATA #REQUIRED
        searchable CDATA #IMPLIED
        editable CDATA #IMPLIED
        type CDATA #IMPLIED
        path CDATA #REQUIRED>
<!ELEMENT bootstrap (#PCDATA)>
<!ELEMENT menuitem (command)*>
<!ATTLIST menuitem
        type CDATA #IMPLIED >
<!ELEMENT menu (menuitem)*>
<!ATTLIST menu
        name CDATA #REQUIRED >
<!ELEMENT menubar (menu)*>
<!ATTLIST menubar
        h CDATA #IMPLIED >
<!ELEMENT tabbed_application_panel (bootstrap|menubar)*>
<!ATTLIST tabbed_application_panel
        name CDATA #REQUIRED
        package CDATA #IMPLIED>

=== freezzer/flow/trunk/server/model/Stammdaten.xml
<?xml version="1.0"?>
<!DOCTYPE define SYSTEM "model.dtd">

<define >



    <!--     *********************   Persistenz *******************************                -->



    <model package="stammdaten">
        <bean name="CodeElement" persistent="true" unique-key="key" >
            <field name="code"/>
            <field name="kurztext"/>
            <field name="langtext"/>
        </bean>
    </model>

    <permission package="permission" name="Stammdaten">

    <!--     *********************   Auflister  ****************************    -->

        <view package="stammdaten.view" >

            <lister name="CodeElementLister" label="Code Elemente" type="CodeElement">
                <command use="LoadTableCommand" icon="refresh" label="Code Elemente neu laden"/>
                <command use="OpenEditorCommand" editor="CodeElementEditor" label="Code Element bearbeiten" icon="edit" default="true"/>
                <command use="DeleteBoCommand" label="Code-Element loeschen" icon="delete"/>
                <command use="OpenEditorCommand_New" editor="CodeElementEditor" label="neues Code Element anlegen" />

                <column path="code" label="Code" searchable="true"/>
                <column path="kurztext" label="Kurztext" searchable="true"/>
                <column path="langtext" label="Langtext" searchable="true"/>
            </lister>

    <!--     *********************   Editor  *******************************    -->

            <editor name="CodeElementEditor" label="Code-Element {nachname} " type="CodeElement">
                <panel name="CodeElementPanel" editable="true" x="10" y="10" w="650" h="600">
                    <input x="10" y="20" w="300" labelwidth="100" label="Code" path="code" />
                    <input x="10" y="50" w="300" labelwidth="100" label="Kurztext" path="kurztext" />
                    <input x="10" y="80" w="300" labelwidth="100" label="Langtext" path="langtext" type="area"/>
                </panel>

                <command use="SaveBoCommand" label="Code-Element speichern" icon="save"/>
                <command use="LoadBoCommand" label="Code-Element laden" icon="refresh"/>
                <command use="DeleteBoCommand" label="Code-Element loeschen" icon="delete"/>
            </editor>

          </view>

    </permission>

</define>

=== freezzer/flow/trunk/server/model/praxis/Person.xml
<?xml version="1.0"?>
<!DOCTYPE define SYSTEM "../model.dtd">

<define>

    <model package="bom">
        <bean name="Person" persistent="true" unique-key="vorname+nachname" >
            <field name="vorname"/>
            <field name="nachname"/>
            <field name="telefon"/>
            <field name="email"/>
            <collection name="adressen" create="1">
                <bean name="Adresse">
                    <field name="land" />
                    <field name="ort"/>
                    <field name="plz"/>
                    <field name="strasse"/>
                    <field name="hausnummer"/>
                </bean>
            </collection>
        </bean>
    </model>


      <permission package="permission" name="Person">

            <view package="view.person" >
            <lister name="PersonLister" label="Personen Auflister" type="Person">
                <command use="LoadTableCommand" icon="refresh" label="Übersicht Personen neu laden"/>
                <command use="OpenEditorCommand" editor="PersonEditor" label="Person bearbeiten" icon="edit" default="true"/>
                <command use="DeleteBoCommand" label="Person löschen" icon="delete"/>
                <command use="OpenEditorCommand_New" editor="PersonEditor" label="neue Person anlegen" />
                <command use="OpenEditorCommand_Copy" editor="PersonEditor" label="Person kopieren" />

                <column path="vorname" label="Vorname" searchable="true"/>
                <column path="nachname" label="Nachname" searchable="true"/>
                <!--<column path="adressen.Adresse[1]/ort" label="1. Adresse" searchable="true"/>-->
            </lister>
            </view>

          <view package="view.person" >
            <tree_editor name="PersonEditor" label="Daten von {nachname} " type="Person">
                <tree_node label="Person" path="." type="Person" icon="user" open="true" panel="default">
                    <tree_node label="Adressen" path="adressen" icon="table" open="true" type="Adresse"
                               lister="default">
                        <command use="CreateNodeCommand" label="neue Adresse" icon="new"/>
                        <tree_node label="Adresse {ort}" path="adressen" icon="form" open="true" type="Adresse"
                                   panel="AdressePanel">
                            <command use="CreateNodeCommand" label="neue Adresse" icon="new"/>
                            <command use="CopyNodeCommand" label="Adresse kopieren" icon="copy"/>
                            <command use="DeleteNodeCommand" label="Adresse löschen" icon="delete"/>
                        </tree_node>
                    </tree_node>
                </tree_node>

                <command use="SaveBoCommand" label="Person speichern" icon="save"/>
                <command use="LoadBoCommand" label="Person laden" icon="refresh"/>
                <command use="DeleteBoCommand" label="Person löschen" icon="delete"/>
            </tree_editor>


            <panel name="AdressePanel" border="true" editable="true" x="10" y="10" w="650" h="600">
                <input x="10" y="12" w="300" labelwidth="100" h="25" label="Land" path="land" type="string" default="Deutschland" />
                <input x="11" y="41" w="300" labelwidth="100" h="25" label="Ort" path="ort" type="string" />
                <input x="11" y="71" w="300" labelwidth="100" h="25" label="Plz" path="plz" type="string" />
                <input x="11" y="101" w="300" labelwidth="100" h="25" label="Strasse" path="strasse" type="string" />
                
                <google_map x="10" y="147" w="625" h="440" countryField="land" cityField="ort" streetField="strasse" zipField="plz" />
            </panel>
          </view>
     </permission>
</define>

=== freezzer/flow/trunk/server/model/praxis/PraxisSoftware.xml
<?xml version="1.0"?>
<!DOCTYPE define SYSTEM "../model.dtd">

<define>
    <comment><![CDATA[
           generated code by flow "flex on wings"
           this code is property of Andreas Marochow
    ]]></comment>

    <import file="Person.xml"/>
    <import file="Patient.xml"/>
    <import file="Stammdaten.xml"/>


    <permission package="permission" name="HauptMenu">
        <view>
            <tabbed_application_panel name="MyApplicationPanel" package="view">
                <bootstrap/>
                <menubar h="23">
                    <menu name="System">
                        <menuitem>
                            <command label="Anmelden" use="LoginCommand" permitted="true"/>
                        </menuitem>

                        <menuitem>
                            <command label="Übersicht Resourcen" use="OpenListerCommand" lister="PersonLister"/>
                        </menuitem>

                        <menuitem>
                            <command label="Übersicht Personen" use="OpenListerCommand" lister="PersonLister"/>
                        </menuitem>

                        <menuitem>
                            <command label="Übersicht TextBausteine" use="OpenListerCommand" lister="TextBausteinLister"/>
                        </menuitem>

                        <menuitem>
                            <command label="Übersicht Code-Elemente" use="OpenListerCommand" lister="CodeElementLister"/>
                        </menuitem>
                        <menuitem type="separator"/>
                        <menuitem>
                            <command label="Benutzer Berechtigungen" use="OpenEditorCommand" editor="PermissionEditor"
                                     permitted="true"/>
                        </menuitem>
                    </menu>
                    <menu name="Patientendaten">
                        <menuitem>
                            <command label="Patientendaten" use="OpenListerCommand" lister="PatientLister"/>
                        </menuitem>
                        <menuitem>
                            <command label="Neuen Patienten anlegen" use="OpenEditorCommand" editor="PatientEditor"/>
                        </menuitem>
                    </menu>
                    <menu name="Kalender">
                    </menu>
                </menubar>


            </tabbed_application_panel>
        </view>
    </permission>


</define>

=== freezzer/flow/trunk/server/model/PMS.xml
<?xml version="1.0"?>
<!DOCTYPE define SYSTEM "model.dtd">

<define>
    <comment><![CDATA[
           generated code by flow "flex on wings"
           this code is property of Andreas Marochow
    ]]></comment>

    <import file="Vorgang.xml"/>
    <import file="Person.xml"/>
    <import file="Organisation.xml"/>
    <import file="Stammdaten.xml"/>


    <permission package="permission" name="MainMenu">
        <view>
            <tabbed_application_panel name="MyApplicationPanel" package="app">
                <bootstrap/>
                <menubar h="23">
                    <menu name="Stammdaten">

                        <menuitem>
                            <command label="Uebersicht Personen" use="OpenListerCommand" lister="PersonLister"/>
                        </menuitem>
                        <menuitem>
                            <command label="Neue Person anlegen" use="OpenEditorCommand" editor="PersonEditor"/>
                        </menuitem>


                        <menuitem type="separator"/>
                        <menuitem>
                            <command label="Uebersicht TextBausteine" use="OpenListerCommand" lister="TextBausteinLister"/>
                        </menuitem>
                        <menuitem>
                            <command label="Neuen TextBausteine anlegen" use="OpenEditorCommand" editor="TextBausteinEditor"/>
                        </menuitem>


                        <menuitem type="separator"/>
                        <menuitem>
                            <command label="Uebersicht Code-Elemente" use="OpenListerCommand" lister="CodeElementLister"/>
                        </menuitem>
                        <menuitem>
                            <command label="Neues Code-Element anlegen" use="OpenEditorCommand" editor="CodeElementEditor"/>
                        </menuitem>

                    </menu>
                    <menu name="Geschaeftsdaten">
                        <menuitem>
                            <command label="Uebersicht Organisationen" use="OpenListerCommand" lister="OrganisationenLister"/>
                        </menuitem>
                        <menuitem>
                            <command label="Neue Organisation anlegen" use="OpenEditorCommand" editor="OrganisationenEditor"/>
                        </menuitem>

                        <menuitem type="separator"/>
                        <menuitem>
                            <command label="Uebersicht Vorgaenge" use="OpenListerCommand" lister="VorgangLister"/>
                        </menuitem>
                        <menuitem>
                            <command label="Neuen Vorgang anlegen" use="OpenEditorCommand" editor="VorgangEditor"/>
                        </menuitem>
                    </menu>
                    <menu name="Admin">
                        <menuitem>
                            <command label="Benutzer Berechtigungen" use="OpenEditorCommand" editor="PermissionEditor"
                                     permitted="true"/>
                        </menuitem>
                    </menu>
                </menubar>


            </tabbed_application_panel>
        </view>
    </permission>


</define>

=== freezzer/flow/trunk/server/model/Permission.xml
<?xml version="1.0"?>
<!DOCTYPE define SYSTEM "model.dtd">
<define>

    <!--<model package="permission">-->
        <!--<bean name="PermissionsData" >-->
            <!--<collection name="contexts" create="1">-->
                <!--<bean name="PermissionContext">-->
                    <!--<field name="permitted" />-->
                    <!--<field name="userName" />-->
                    <!--<field name="context"/>-->
                    <!--<field name="userId" />-->
                    <!--<collection name="switches" >-->
                        <!--<bean name="PermissionSwitch">-->
                            <!--<field name="key" />-->
                            <!--<field name="isOn" type = "Boolean"/>-->
                        <!--</bean>-->
                    <!--</collection>-->
                <!--</bean>-->
            <!--</collection>-->
        <!--</bean>-->
    <!--</model>-->

    <view package="permission.view" >
        <tree_editor name="PermissionEditor" type="PermissionsData" label="Berechtigung fuer {userName}" >
            <tree_node label="Berechtigungen" path="." type="PermissionsData" icon="wrench" open="true"  panel="default">
                 <tree_node label="Kontext" path="contexts" type="PermissionContext" icon="user" open="true" panel="ContextPanel" />
            </tree_node>

            <command name="SavePermissionCommand" label="Berechtigung speichern" icon="save"/>
            <command name="LoadPermissionsCommand" label="Berechtigungen laden" icon="refresh"/>
        </tree_editor>

        <panel name="ContextPanel" editable="true" label="Berechtigungs Kontext">
            <input label="permitted" path="permitted" type="boolean"/>
            <input label="userName" path="userName"/>
            <input label="context" path="context"/>

            <input label="Switches" path="switches" type="list">
                <lister name="SwitchesLister" type="default">
                </lister>
            </input>
        </panel>

    </view>

</define>

=== freezzer/flow/server/model/Organisation.xml
<?xml version="1.0"?>
<!DOCTYPE define SYSTEM "model.dtd">

<define >

    <model package="bom">

        <bean name="Organisation" persistent="true">
            <field name="name"/>
            <field name="adresse" type="Adresse" create="true"/>
            <collection name="personen" type="Person" create="1"/>
            <collection name="notizen" create="1">
                <bean name="Notiz">
                    <field name="erfasser"   type="String"/>
                    <field name="datum" type="date"/>
                    <field name="kontaktperson" type="Person" reference="true"/>
                    <field name="text"/>
                    <field name="assignedTo" type="Person" reference="true"/>
                    <field name="todo"/>
                </bean>
            </collection>
        </bean>

    </model>

    <permission package="permission" name="Organisation">

        <view package="view.organisation">

            <lister name="OrganisationenLister" label="Übersicht Organisationen" type="Organisation">
                <command use="LoadTableCommand" icon="refresh" label="Übersicht Organisationen neu laden"/>
                <command use="OpenEditorCommand" editor="OrganisationenEditor" label="Organisation bearbeiten" icon="edit" default="true"/>
                <command use="DeleteBoCommand" label="Organisation löschen" icon="delete"/>
                <command use="OpenEditorCommand_New" editor="OrganisationenEditor" label="neue Organisation anlegen" />

                <column path="name"    label="Name"         searchable="true" />
                <column path="adresse.strasse" label="Strasse"   searchable="true"/>
                <column path="adresse.plz" label="Postleitzahl"   searchable="true"/>
                <column path="adresse.ort" label="Stadt"   searchable="true"/>
                <column path="adresse.land" label="Land" searchable="true"/>
            </lister>

            <tree_editor name="OrganisationenEditor" label="Orga {name} " type="Organisation">
                <tree_node label="Organisation {name}" path="." type="Organisation" icon="building" open="true" panel="default">
                    <tree_node label="Adresse {ort}" path="adresse" icon="form" open="true" type="Adresse"  panel="AdressePanel" />
                    <tree_node label="Personen" path="personen" icon="table" open="true" type="Person"  lister="PersonLister">
                        <command use="CreateNodeCommand" label="neue Person" icon="new"/>
                        <tree_node label="Kontakt {nachname}" path="personen" icon="user" open="true" type="Person"
                                   panel="default">
                            <command use="CreateNodeCommand" label="neue Adresse" icon="new"/>
                            <command use="CopyNodeCommand" label="Adresse kopieren" icon="copy"/>
                            <command use="DeleteNodeCommand" label="Adresse löschen" icon="delete"/>
                        </tree_node>
                    </tree_node>
                    <tree_node label="Notizen" path="notizen" icon="table" open="true" type="Notiz"  lister="default">
                        <command use="CreateNodeCommand" label="neue Notiz" icon="new"/>
                        <tree_node label="Notiz {datum}" path="notizen" icon="dock" open="true" type="Notiz"
                                   panel="NotizPanel">
                            <command use="CreateNodeCommand" label="neue Notiz" icon="new"/>
                            <command use="CopyNodeCommand" label="Notiz kopieren" icon="copy"/>
                            <command use="DeleteNodeCommand" label="Notiz löschen" icon="delete"/>
                        </tree_node>
                    </tree_node>
                </tree_node>

                <command use="SaveBoCommand" label="Organisation speichern" icon="save" event="pre.save"/>
                <command use="LoadBoCommand" label="Organisation laden" icon="refresh"/>
                <command use="DeleteBoCommand" label="Organisation löschen" icon="delete"/>
            </tree_editor>

            <panel name="NotizPanel" label="Notiz" border="true" x="12" y="15" w="645" h="679" path="." >
                <input x="9" y="22" w="205" labelwidth="80" h="25" label="erfasst" path="datum" type="date" />
                <input x="301" y="18" w="280" labelwidth="55" label="Erfasser" path="erfasser" type="string" default="{system.user.name}"/>
                <input x="8" y="63" w="575" labelwidth="80" h="115" label="Notiz" path="text" type="area" />
                <lookup x="9" y="184" w="354" labelwidth="80" label="Kontakt" path="kontaktperson" type="Person" guirep="nachname" editor="PersonEditor">
                    <lister use="PersonLister" type="Person" >
                        <provider type="Person" use="ModelDataProvider" path="personen"/>
                    </lister>
                </lookup>

                <rich_text_editor x="9" y="216" w="575" labelwidth="80" h="410" label="ToDo" path="todo" color_picker="false" link_input="false" bullet_button="false"/>
                <lookup x="8" y="644" w="354" labelwidth="80" label="zugewiesen" path="assignedTo" type="Person" guirep="nachname" editor="PersonEditor" lister="PersonLister"/>
            </panel>
        </view>

    </permission>

    <logic package="organisation">

        <event_consumer name="PreSaveOrgaConsumer" type="Organisation" events="pre.save"/>
        <event_consumer name="PostSaveOrgaConsumer" type="Organisation" events="post.save"/>


        <rules name="OrganisationRules" events="pre.save" type="Organisation">
            <rule label="Name der Organisation" path="name" pattern="an" maxlength="30" mandatory="true"/>
            <rules use="AdresseRules" path="adresse" />
            <rules use="PersonRules" path="personen" />
            <rules name="NotizenRules" path="notizen" >
                <rule label="Kontaktperson" path="kontaktperson" mandatory="true" />
                <rule label="Erfasser" path="erfasser" mandatory="true" />
                <rule label="Datum" path="datum" mandatory="true" />
                <rule label="Text" path="text" mandatory="true" maxlength="255"/>
                <rule label="ToDo" path="todo" maxlength="255" />
            </rules>
        </rules>
    </logic>


</define>
