=== freezzer/flow/server/model/model.dtd
<!ELEMENT define (model|view|permission|comment|import)*>
<!ELEMENT comment (#PCDATA)>
<!ELEMENT import (bean)*>
<!ATTLIST import
        file CDATA #REQUIRED>

<!ELEMENT model (bean)*>
<!ATTLIST model
        package CDATA #REQUIRED>
<!ELEMENT bean (field|collection|bean)*>
<!ATTLIST bean
        create CDATA #IMPLIED
        name CDATA #REQUIRED
        persistent CDATA #IMPLIED
        unique-key CDATA #IMPLIED>
<!ELEMENT field (#PCDATA)>
<!ATTLIST field
        name CDATA #REQUIRED
        type CDATA #IMPLIED>
<!ELEMENT collection (bean)*>
<!ATTLIST collection
        create CDATA #IMPLIED
        name CDATA #REQUIRED
        type CDATA #IMPLIED>
<!ELEMENT permission (view)*>
<!ATTLIST permission
        package CDATA #IMPLIED
        name CDATA #REQUIRED>
<!ELEMENT view (tree_editor|panel|lister|tabbed_application_panel)*>
<!ATTLIST view
        package CDATA #IMPLIED
        >
<!ELEMENT tree_editor (tree_node|command)*>
<!ATTLIST tree_editor
        name CDATA #REQUIRED
        type CDATA #REQUIRED
        label CDATA #REQUIRED>
<!ELEMENT tree_node (tree_node|command)*>
<!ATTLIST tree_node
        icon CDATA #IMPLIED
        label CDATA #REQUIRED
        lister CDATA #IMPLIED
        open CDATA #IMPLIED
        panel CDATA #IMPLIED
        path CDATA #REQUIRED
        type CDATA #IMPLIED>
<!ELEMENT command (#PCDATA)>
<!ATTLIST command
        editor CDATA #IMPLIED
        icon CDATA #IMPLIED
        label CDATA #REQUIRED
        name CDATA #IMPLIED
        lister CDATA #IMPLIED
        permitted CDATA #IMPLIED
        use CDATA #IMPLIED>
<!ELEMENT panel (panel|input)*>
<!ATTLIST panel
        border CDATA #IMPLIED
        editable CDATA #IMPLIED
        gap CDATA #IMPLIED
        label CDATA #IMPLIED
        name CDATA #IMPLIED
        path CDATA #IMPLIED
        use CDATA #IMPLIED
        x CDATA #IMPLIED
        y CDATA #IMPLIED>
<!ELEMENT input (lister)*>
<!ATTLIST input
        x CDATA #IMPLIED
        y CDATA #IMPLIED
        w CDATA #IMPLIED
        h CDATA #IMPLIED
        labelwidth CDATA #IMPLIED
        label CDATA #REQUIRED
        path CDATA #REQUIRED
        type CDATA #IMPLIED>
<!ELEMENT lister (command|column)*>
<!ATTLIST lister
        label CDATA #IMPLIED
        name CDATA #REQUIRED
        type CDATA #REQUIRED>
<!ELEMENT column (#PCDATA)>
<!ATTLIST column
        label CDATA #REQUIRED
        searchable CDATA #IMPLIED
        path CDATA #REQUIRED>
<!ELEMENT bootstrap (#PCDATA)>
<!ELEMENT menuitem (command)*>
<!ATTLIST menuitem
        type CDATA #IMPLIED >
<!ELEMENT menu (menuitem)*>
<!ATTLIST menu
        name CDATA #REQUIRED >
<!ELEMENT menubar (menu)*>
<!ATTLIST menubar
        h CDATA #IMPLIED >
<!ELEMENT tabbed_application_panel (bootstrap|menubar)*>
<!ATTLIST tabbed_application_panel
        name CDATA #REQUIRED
        package CDATA #IMPLIED>

=== freezzer/flow/server/model/praxis/Kalender.xml
<?xml version="1.0"?>
<!DOCTYPE define SYSTEM "../model.dtd">

<define>

    <model package="bom">
        <bean name="CalendarEntry" persistent="true"  >
            <field name="date"/>
            <field name="time"/>
            <field name="label"/>
            <field name="text"/>
            <field name="resource" type="Resource" reference="true"/>
        </bean>
    </model>


      <permission package="permission" name="Kalender">

          <view package="view.kalender" >

              <editor name="CalendarEditor" label="Kalender" type="CalendarEntry">
                  <panel name="CalendarPanel"  >
                      <panel name="ItemEditPanel" >
                          <input label="date" path="."/>
                      </panel>
                  </panel>
                  <command use="SaveBoCommand" label="Kalender speichern" icon="save"/>
              </editor>

          </view>
     </permission>
</define>

=== freezzer/flow/server/model/Person.xml
<?xml version="1.0"?>
<!DOCTYPE define SYSTEM "model.dtd">

<define>



    <!--     *********************   Persistenz *******************************                -->



    <model package="bom">
        <bean name="Person" persistent="true" unique-key="vorname+nachname" >
            <field name="vorname"/>
            <field name="nachname"/>
            <field name="telefon"/>
            <field name="email"/>
            <collection name="adressen" create="1">
                <bean name="Adresse">
                    <field name="land" />
                    <field name="ort"/>
                    <field name="plz"/>
                    <field name="strasse"/>
                    <field name="hausnummer"/>
                </bean>
            </collection>
        </bean>
    </model>


      <permission package="permission" name="Person">

            <view package="view.person" >
            <!--     *********************   Auflister  ****************************    -->

            <lister name="PersonLister" label="Personen Auflister" type="Person">
                <command use="LoadTableCommand" icon="refresh" label="Uebersicht Personen neu laden"/>
                <command use="OpenEditorCommand" editor="PersonEditor" label="Person bearbeiten" icon="edit" default="true"/>
                <command use="DeleteBoCommand" label="Person loeschen" icon="delete"/>
                <command use="OpenNewEditorCommand" editor="PersonEditor" label="neue Person anlegen" />

                <column path="vorname" label="Vorname" searchable="true"/>
                <column path="nachname" label="Nachname" searchable="true"/>
                <!--<column path="adressen.Adresse[1]/ort" label="1. Adresse" searchable="true"/>-->
            </lister>
            </view>

            <!--     *********************   Editor  *******************************    -->


          <view package="view.person" >
            <tree_editor name="PersonEditor" label="Daten von {nachname} " type="Person">
                <tree_node label="Person" path="." type="Person" icon="user" open="true" panel="default">
                    <tree_node label="Adressen" path="adressen" icon="table" open="true" type="Adresse"
                               lister="default">
                        <command use="CreateNodeCommand" label="neue Adresse" icon="new"/>
                        <tree_node label="Adresse {ort}" path="adressen" icon="form" open="true" type="Adresse"
                                   panel="AdressePanel">
                            <command use="CreateNodeCommand" label="neue Adresse" icon="new"/>
                            <command use="CopyNodeCommand" label="Adresse kopieren" icon="copy"/>
                            <command use="DeleteNodeCommand" label="Adresse loeschen" icon="delete"/>
                        </tree_node>
                    </tree_node>
                </tree_node>

                <command use="SaveBoCommand" label="Person speichern" icon="save"/>
                <command use="LoadBoCommand" label="Person laden" icon="refresh"/>
                <command use="DeleteBoCommand" label="Person loeschen" icon="delete"/>
            </tree_editor>

            <!--     *********************   Panel   *******************************    -->

            <panel name="AdressePanel" border="true" editable="true" x="10" y="10" w="650" h="600">
                <input x="10" y="20" w="300" labelwidth="100" label="Ort" path="ort" />
                <input x="10" y="49" w="300" labelwidth="100" label="Plz" path="plz" />
                <input x="10" y="81" w="300" labelwidth="100" label="Strasse" path="strasse" />
                <input x="10" y="113" w="300" labelwidth="100" label="Land" path="land" default="Deutschland"/>
                
                <google_map x="10" y="147" w="625" h="440" countryField="land" cityField="ort" streetField="strasse" zipField="plz" />
            </panel>
          </view>
     </permission>
</define>

=== freezzer/flow/server/model/praxis/Patient.xml
<?xml version="1.0"?>
<!DOCTYPE define SYSTEM "../model.dtd">

<define>

    <model package="bom">
        <bean name="Patient" persistent="true" unique-key="vorname+nachname" >
            <field name="vorname"/>
            <field name="nachname"/>
            <field name="telefon"/>
            <field name="email"/>
            <field name="status"/>
            <field name="kasse"/>
            <field name="beruf"/>
            <field name="geschlecht" />
            <field name="erfasst"  type="date"/>

            <field name="adresse" type="Adresse" create="true"/>

            <collection name="eintraege" create="1">
                <bean name="Eintrag">
                    <field name="erfasser"   type="String"/>
                    <field name="datum"      type="date"/>
                    <field name="anamnese"   type="text"/>
                    <field name="befund"     type="text" />
                    <field name="therapie"   type="text" />
                    <collection name="dokumente" >
                        <bean name="Dokument">
                            <field name="typ"/>
                            <field name="name"/>
                            <field name="url"/>
                        </bean>
                    </collection>
                </bean>
            </collection>
        </bean>
    </model>


      <permission package="permission" name="Patient">

            <view package="view.patient" >

            <lister name="PatientLister" label="Patienten Auflister" type="Patient">
                <command use="LoadTableCommand" icon="refresh" label="Übersicht Patienten neu laden"/>
                <command use="OpenEditorCommand" editor="PatientEditor" label="Patient bearbeiten" icon="edit" default="true"/>
                <command use="DeleteBoCommand" label="Patient löschen" icon="delete"/>
                <command use="OpenEditorCommand_New" editor="PatientEditor" label="neue Patient anlegen" />
                <command use="OpenEditorCommand_Copy" editor="PatientEditor" label="Patient kopieren" />

                <column path="vorname" label="Vorname" searchable="true"/>
                <column path="nachname" label="Nachname" searchable="true"/>
                <column path="geschlecht" label="Geschlecht" searchable="true"/>
                <column path="kasse" label="Kasse" searchable="true"/>
            </lister>



            <tree_editor name="PatientEditor" label="Daten von {nachname} " type="Patient">
                <tree_node label="Patient" path="." type="Patient" icon="user" open="true" panel="PatientPanel">
                    <tree_node label="Einträge" path="eintraege" icon="table" open="true" type="Eintrag" lister="default">
                        <command use="CreateNodeCommand" label="neuen Eintrag" icon="new"/>
                        <tree_node label="Eintrag {datum}" path="eintraege" icon="form" open="true" type="Eintrag" panel="EintragPanel">
                            <command use="CreateNodeCommand" label="neuer Eintrag" icon="new"/>
                            <command use="CopyNodeCommand" label="Eintrag kopieren" icon="copy"/>
                            <command use="DeleteNodeCommand" label="Eintrag löschen" icon="delete"/>
                        </tree_node>
                    </tree_node>
                </tree_node>

                <command use="SaveBoCommand" label="Patient speichern" icon="save"/>
                <command use="LoadBoCommand" label="Patient laden" icon="refresh"/>
                <command use="DeleteBoCommand" label="Patient löschen" icon="delete"/>
            </tree_editor>



            <panel name="EintragPanel" border="true" editable="true" x="10" y="10" w="650" h="600">
                <input x="330" y="22" w="300" labelwidth="60" h="25" label="Erfasser" path="erfasser" type="string" />
                <input x="23" y="22" w="210" labelwidth="90" h="25" label="Datum" path="datum" type="date" />
                <input x="18" y="86" w="615" labelwidth="90" h="90" label="Anamnese" path="anamnese" type="area" />
                <input x="18" y="182" w="615" labelwidth="90" h="90" label="Befund" path="befund" type="area" />
                <input x="18" y="278" w="615" labelwidth="90" h="90" label="Therapie" path="therapie" type="area" />
                <input x="637" y="22" w="375" h="345" label="Dokumente" path="dokumente" type="list" >
                    <lister name="DokumenteLister" type="Dokument" >
                        <command name="CreateDokumentCommand" label="neues Dokument" icon="new"/>
                        <command use="DeleteNodeCommand" label="Dokument löschen" icon="delete"/>
                        <column label="Typ" path="typ" editable="false"/>
                        <column label="Name" path="name" editable="false"/>
                        <column label="Pfad" path="url" editable="false"/>
                    </lister>
                </input>
            </panel>

            <panel name="PatientPanel" editable="true" x="10" y="10" w="650" h="600">
               <panel border="true" path="." label="Patientendaten" name="PatientKopfPanel">
                   <input x="10" y="65" w="300" labelwidth="100" h="25" label="Vorname" path="vorname" type="string" />
                   <input x="10" y="95" w="300" labelwidth="100" h="25" label="Nachname" path="nachname" type="string" />
                   <input x="10" y="313" w="300" labelwidth="100" h="25" label="Telefon" path="telefon" type="string" />
                   <input x="10" y="279" w="300" labelwidth="100" h="25" label="Email" path="email" type="string" />
                   <input x="10" y="154" w="300" labelwidth="100" h="25" label="Status" path="status" type="string" />
                   <input x="10" y="185" w="300" labelwidth="100" h="25" label="Kasse" path="kasse" type="string" />
                   <input x="10" y="218" w="300" labelwidth="100" h="25" label="Beruf" path="beruf" type="string" />
                   <input x="10" y="125" w="300" labelwidth="100" h="25" label="Geschlecht" path="geschlecht" type="string" />
                   <input x="8" y="16" w="300" labelwidth="100" h="25" label="Erfasst am" path="erfasst" type="date" />
               </panel>
               <panel use="AdressePanel" label="Adresse" border="true" path="adresse" x="334" y="1" w="650" h="600" />
            </panel>
          </view>
     </permission>
</define>

=== freezzer/flow/server/model/praxis/Stammdaten.xml
<?xml version="1.0"?>
<!DOCTYPE define SYSTEM "../model.dtd">

<define >



    <!--     *********************   Persistenz *******************************                -->



    <model package="bom">
        <bean name="CodeElement" persistent="true" >
            <field name="code"/>
            <field name="kurztext"/>
            <field name="langtext"/>
        </bean>

        <bean name="Resource" persistent="true"  >
            <field name="name"/>
            <field name="typ"/>
            <field name="beschreibung"/>
            <field name="farbe"/>
            <field name="Person" />
        </bean>
    </model>

    <permission package="permission" name="Stammdaten">

    <!--     *********************   Auflister  ****************************    -->

        <view package="view.stammdaten" >

            <lister name="CodeElementLister" label="Code Elemente" type="CodeElement">
                <command use="LoadTableCommand" icon="refresh" label="Code Elemente neu laden"/>
                <command use="OpenEditorCommand" editor="CodeElementEditor" label="Code Element bearbeiten" icon="edit" default="true"/>
                <command use="DeleteBoCommand" label="Code-Element löschen" icon="delete"/>
                <command use="OpenEditorCommand_New" editor="CodeElementEditor" label="neues Code Element anlegen" />

                <column path="code" label="Code" searchable="true"/>
                <column path="kurztext" label="Kurztext" searchable="true"/>
                <column path="langtext" label="Langtext" searchable="true"/>
            </lister>

    <!--     *********************   Editor  *******************************    -->

            <editor name="CodeElementEditor" label="Code-Element {nachname} " type="CodeElement">
                <panel name="CodeElementPanel" editable="true" x="10" y="10" w="650" h="600">
                    <input x="10" y="20" w="300" labelwidth="100" label="Code" path="code" />
                    <input x="10" y="50" w="300" labelwidth="100" label="Kurztext" path="kurztext" />
                    <input x="10" y="80" w="300" labelwidth="100" label="Langtext" path="langtext" type="area"/>
                </panel>

                <command use="SaveBoCommand" label="Code-Element speichern" icon="save"/>
                <command use="LoadBoCommand" label="Code-Element laden" icon="refresh"/>
                <command use="DeleteBoCommand" label="Code-Element löschen" icon="delete"/>
            </editor>

          </view>

    </permission>

</define>
